admin_orders_view:
  path: /orders/{orderId}/view
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShop\Module\Lengow\Controller\AdminOrderController::viewAction'
    _legacy_controller: AdminOrders
    _legacy_link: AdminOrders
    _legacy_parameters:
      id_order: orderId
  options:
    expose: true
  requirements:
    orderId: \d+
